export const ENGINEERING_READ_ROLES = [
  'ADMIN', 'MANAGEMENT', 'SALES', 'DESIGN', 'PLANNING', 'PRODUCTION', 'QUALITY', 'CUSTOMER',
];

export const ENGINEERING_WRITE_ROLES = ['ADMIN', 'MANAGEMENT', 'DESIGN', 'PLANNING'];
