"""
PMM Data Library — Prathiraj Metal Masters Master Data Library
===============================================================

A reusable Python data-access layer for Blow Mold (BM) and Injection Mold (IM)
project data, consolidated from multiple Excel files across different teams
and time periods.

Usage in your VS Code project:
    from pmm_data_library import BlowMoldDB, InjectionMoldDB, normalize_tool_number

    # Query all blow molds
    db = BlowMoldDB()
    molds = db.get_all()
    
    # Search by project number (BMXXX format)
    mold = db.get_by_project_no("BM243")
    
    # Search by customer
    alpla_molds = db.search_by_customer("ALPLA")

Tables:
    • blow_molds              — 1,142 records
    • injection_molds         — 127 records
    • job_works               — 517 records
    • alpla_std_parts         — 91 records
    • commercial_molds        — 115 records
    • part_list_summaries     — 8 records (BM450, BM458, BM475)
    • part_list_details       — 712 records (individual parts)

Normalization Rules:
    • M-xxx   → BMxxx   (early blow mold numbering)
    • BM-xxx  → BMxxx   (current blow mold numbering)
    • T-xxxx  → T-xxxx  (legacy/customer tool numbers, kept as-is)
    • IM-xx   → IMxxx   (injection mold numbering, 3-digit padded)
    • CMB-xx  → CMBxxx  (commercial mold bases)
    • S-xx    → S-xx    (job works / spares, kept as-is)

Author: Auto-generated by PMM Data Consolidation Tool
Date: 2025-06-29
"""

from .db import BlowMoldDB, InjectionMoldDB, JobWorkDB, ALPLAStdPartsDB, CommercialMoldDB, MasterDataDB, PartListSummaryDB, PartListDetailDB
from .utils import normalize_tool_number, infer_project_type
from .models import BlowMold, InjectionMold, JobWork, ALPLAStdPart, CommercialMold, PartListSummary, PartListDetail

__version__ = "1.0.0"
__all__ = [
    "BlowMoldDB",
    "InjectionMoldDB",
    "JobWorkDB",
    "ALPLAStdPartsDB",
    "CommercialMoldDB",
    "MasterDataDB",
    "PartListSummaryDB",
    "PartListDetailDB",
    "normalize_tool_number",
    "infer_project_type",
    "BlowMold",
    "InjectionMold",
    "JobWork",
    "ALPLAStdPart",
    "CommercialMold",
    "PartListSummary",
    "PartListDetail",
]
