/**
 * Sprint 2.8.3 — Enterprise AI Copilot capability catalogue.
 *
 * Single source of truth for the 7 domain copilots and their ~55
 * capabilities. Each capability declares:
 *   - promptKey      : the Prompt Registry task used for the chat pipeline
 *   - tools          : auto-attached tools executed by the platform pipeline
 *   - intentPatterns : lightweight intent detection for capability routing
 *   - suggestedActions / followUpQuestions : UX guidance surfaced to users
 */

import { CopilotDomain } from '../dto/copilot.dto';

export interface CopilotCapability {
  key: string;
  title: string;
  description: string;
  promptKey: string;
  tools: string[];
  intentPatterns: RegExp[];
  suggestedActions: string[];
  followUpQuestions: string[];
}

export interface CopilotDefinition {
  domain: CopilotDomain;
  label: string;
  description: string;
  capabilities: CopilotCapability[];
}

export const COPILOT_CATALOGUE: CopilotDefinition[] = [
  {
    domain: CopilotDomain.ENGINEERING,
    label: 'Engineering Copilot',
    description: 'Drawing, BOM, process-planning, and engineering-review assistance grounded in released engineering records.',
    capabilities: [
      {
        key: 'engineering.drawings.explain',
        title: 'Explain a drawing',
        description: 'Explain the referenced drawing, dimensions, revisions, and linked BOM/routing/process documents.',
        promptKey: 'engineering.explain_drawing',
        tools: ['engineering.drawings'],
        intentPatterns: [/explain (this |the )?drawing/i, /what is drawing/i, /drawing (details|overview|summary)/i],
        suggestedActions: ['Compare revisions', 'Find similar drawings', 'Review manufacturing impact'],
        followUpQuestions: ['What are the latest revisions?', 'Which BOM items does this drawing release?', 'Are there similar drawings?'],
      },
      {
        key: 'engineering.drawings.revision_compare',
        title: 'Compare revisions',
        description: 'Compare engineering revisions and summarize release-impacting changes.',
        promptKey: 'engineering.compare_revisions',
        tools: ['engineering.drawings'],
        intentPatterns: [/compare (revisions|revs|changes)/i, /what changed (in|between) revision/i, /revision (diff|delta|changes)/i],
        suggestedActions: ['Explain the drawing', 'Review manufacturing impact'],
        followUpQuestions: ['What changed between rev A and rev B?', 'Which changes are release-impacting?'],
      },
      {
        key: 'engineering.drawings.manufacturing_impact',
        title: 'Manufacturing impact of a change',
        description: 'Assess how a drawing change impacts routings, work orders, and downstream production.',
        promptKey: 'engineering.manufacturing_impact',
        tools: ['engineering.drawings', 'engineering.routings', 'manufacturing.work_orders'],
        intentPatterns: [/manufacturing impact/i, /impact of (the |this )?change/i, /what (does|is) .*affect(ing)?/i],
        suggestedActions: ['Explain the drawing', 'Compare revisions', 'Review process plans'],
        followUpQuestions: ['Which routings reference this drawing?', 'Are there open work orders?'],
      },
      {
        key: 'engineering.drawings.similar',
        title: 'Find similar drawings',
        description: 'Find similar drawings and explain why they are similar using source references.',
        promptKey: 'engineering.find_similar_drawings',
        tools: ['engineering.drawings'],
        intentPatterns: [/similar drawings/i, /find (similar|related) drawings/i, /other drawings (like|similar to)/i],
        suggestedActions: ['Explain a drawing', 'Compare revisions'],
        followUpQuestions: ['Which drawings are most similar?', 'Why are they similar?'],
      },
      {
        key: 'engineering.bom.explain',
        title: 'Explain a BOM',
        description: 'Explain BOM structure, critical items, release status, and linked drawing/routing references.',
        promptKey: 'engineering.explain_bom',
        tools: ['engineering.boms'],
        intentPatterns: [/explain (the |this )?(bom|bill of materials)/i, /bom (structure|overview|details)/i, /bill of materials/i],
        suggestedActions: ['Find missing components', 'Analyze BOM cost', 'Suggest alternate materials'],
        followUpQuestions: ['Which items are critical?', 'What is the release status?', 'Which drawings are linked?'],
      },
      {
        key: 'engineering.bom.gap_analysis',
        title: 'BOM gap analysis',
        description: 'Identify missing components and duplicate part numbers in a BOM.',
        promptKey: 'engineering.bom_gap_analysis',
        tools: ['engineering.boms', 'engineering.drawings'],
        intentPatterns: [/missing (components|parts|items)/i, /duplicate parts?/i, /bom (gap|issues|problems)/i, /incomplete bom/i],
        suggestedActions: ['Explain the BOM', 'Analyze BOM cost'],
        followUpQuestions: ['Which components are missing?', 'Are there duplicate part numbers?'],
      },
      {
        key: 'engineering.bom.cost_analysis',
        title: 'BOM cost analysis',
        description: 'Analyze BOM item cost drivers and identify cost reduction opportunities.',
        promptKey: 'engineering.bom_cost_analysis',
        tools: ['engineering.boms', 'engineering.routings'],
        intentPatterns: [/bom cost/i, /cost analysis of (the )?bom/i, /expensive (items|components|parts)/i, /cost drivers/i],
        suggestedActions: ['Suggest alternate materials', 'Explain the BOM'],
        followUpQuestions: ['Which items drive cost?', 'Where can costs be reduced?'],
      },
      {
        key: 'engineering.bom.alternate_materials',
        title: 'Alternate materials',
        description: 'Suggest alternate materials or substitutes supported by BOM and knowledge references.',
        promptKey: 'engineering.alternate_materials',
        tools: ['engineering.boms', 'knowledge.search'],
        intentPatterns: [/alternate (material|materials|part)/i, /substitut(e|es|ion)/i, /replace(ment)? (material|part)/i],
        suggestedActions: ['Analyze BOM cost', 'Explain the BOM'],
        followUpQuestions: ['Which materials can be substituted?', 'Are substitutes qualified?'],
      },
      {
        key: 'engineering.routing.explain',
        title: 'Explain a process plan / routing',
        description: 'Summarize process plans and routing operations from released engineering context.',
        promptKey: 'engineering.summarize_process_plans',
        tools: ['engineering.routings'],
        intentPatterns: [/explain (the |this )?(routing|process plan)/i, /process plan (details|overview)/i, /routing operations/i],
        suggestedActions: ['Review cycle times', 'Optimize operations', 'Check machine selection'],
        followUpQuestions: ['What are the operations?', 'Which machines are assigned?'],
      },
      {
        key: 'engineering.routing.cycle_time',
        title: 'Cycle-time analysis',
        description: 'Review cycle-time observations and compare against planned operation times.',
        promptKey: 'engineering.cycle_time_analysis',
        tools: ['engineering.routings', 'manufacturing.work_orders'],
        intentPatterns: [/cycle time/i, /process time/i, /operation time/i],
        suggestedActions: ['Optimize operations', 'Review machine utilization'],
        followUpQuestions: ['Where do actual times exceed planned?', 'Which operations are bottlenecks?'],
      },
      {
        key: 'engineering.routing.optimization',
        title: 'Operation optimization',
        description: 'Recommend routing/operation improvements grounded in available production records.',
        promptKey: 'engineering.operation_optimization',
        tools: ['engineering.routings', 'manufacturing.work_orders'],
        intentPatterns: [/optimiz(e|ation) (operations|routing|process)/i, /improve (the )?(routing|process|operation)/i],
        suggestedActions: ['Review cycle times', 'Check machine selection'],
        followUpQuestions: ['Which operations should be reviewed?', 'What evidence supports the change?'],
      },
      {
        key: 'engineering.routing.machine_selection',
        title: 'Machine selection advice',
        description: 'Advise on machine selection for operations supported by routing and knowledge references.',
        promptKey: 'engineering.machine_selection',
        tools: ['engineering.routings', 'knowledge.search'],
        intentPatterns: [/machine selection/i, /which machine/i, /best machine for/i, /machine (for|suitable)/i],
        suggestedActions: ['Review cycle times', 'Check capacity assessment'],
        followUpQuestions: ['Which machines can run this operation?', 'What is the utilization outlook?'],
      },
      {
        key: 'engineering.review.design_review',
        title: 'Engineering design review',
        description: 'Support design reviews by summarizing drawings, BOMs, and release constraints.',
        promptKey: 'engineering.design_review',
        tools: ['engineering.drawings', 'engineering.boms'],
        intentPatterns: [/design review/i, /review (the )?design/i, /engineering review/i],
        suggestedActions: ['DFM recommendations', 'Risk identification'],
        followUpQuestions: ['Which items need review?', 'Are there open risks?'],
      },
      {
        key: 'engineering.review.dfm',
        title: 'DFM recommendations',
        description: 'Provide design-for-manufacturing recommendations grounded in drawings and routings.',
        promptKey: 'engineering.dfm_recommendations',
        tools: ['engineering.drawings', 'engineering.routings'],
        intentPatterns: [/dfm/i, /design for manufactur/i, /manufacturability/i],
        suggestedActions: ['Design review', 'Risk identification'],
        followUpQuestions: ['Which features are hard to manufacture?', 'What changes would help?'],
      },
      {
        key: 'engineering.review.risk',
        title: 'Engineering risk identification',
        description: 'Identify engineering risks from drawings, BOMs, and linked quality records.',
        promptKey: 'engineering.risk_identification',
        tools: ['engineering.drawings', 'engineering.boms', 'quality.ncrs'],
        intentPatterns: [/engineering risk/i, /risks? (in|for|related to) (design|drawing|bom)/i, /risk identification/i],
        suggestedActions: ['Design review', 'DFM recommendations'],
        followUpQuestions: ['Which risks are critical?', 'Are there linked NCRs?'],
      },
    ],
  },
  {
    domain: CopilotDomain.MANUFACTURING,
    label: 'Manufacturing Copilot',
    description: 'Work-order, machine utilization, delay, scrap, downtime, OEE, scheduling, and capacity assistance.',
    capabilities: [
      {
        key: 'manufacturing.work_orders.status',
        title: 'Work order status',
        description: 'Summarize work order progress, operation status, schedule impact, and blockers.',
        promptKey: 'manufacturing.production_summary',
        tools: ['manufacturing.work_orders'],
        intentPatterns: [/work order (status|progress|summary)/i, /how (is|are) (the )?work orders?/i, /production (status|progress)/i],
        suggestedActions: ['Analyze delays', 'Check scrap', 'Review machine utilization'],
        followUpQuestions: ['Which work orders are behind?', 'What is blocking production?'],
      },
      {
        key: 'manufacturing.machines.utilization',
        title: 'Machine utilization',
        description: 'Summarize machine utilization context from available production records.',
        promptKey: 'manufacturing.machine_utilization',
        tools: ['manufacturing.work_orders'],
        intentPatterns: [/machine utilization/i, /utilization (of )?machines?/i, /how utilized/i],
        suggestedActions: ['Capacity assessment', 'Downtime analysis'],
        followUpQuestions: ['Which machines are overloaded?', 'Which are idle?'],
      },
      {
        key: 'manufacturing.delays.analysis',
        title: 'Production delay analysis',
        description: 'Analyze production delays and their impact on schedules and deliveries.',
        promptKey: 'manufacturing.delay_analysis',
        tools: ['manufacturing.work_orders'],
        intentPatterns: [/delay/i, /behind schedule/i, /late (work order|orders|production)/i, /slippage/i],
        suggestedActions: ['Work order status', 'Schedule recommendations'],
        followUpQuestions: ['What caused the delay?', 'Which orders are affected?'],
      },
      {
        key: 'manufacturing.scrap.explain',
        title: 'Scrap analysis',
        description: 'Explain scrap records, likely source operations, and quality follow-up references.',
        promptKey: 'manufacturing.explain_scrap',
        tools: ['manufacturing.work_orders', 'quality.ncrs'],
        intentPatterns: [/scrap/i, /rejected (parts|quantity)/i, /yield issue/i],
        suggestedActions: ['Root cause analysis', 'Work order status'],
        followUpQuestions: ['Which operations scrap the most?', 'Are NCRs linked?'],
      },
      {
        key: 'manufacturing.downtime.analysis',
        title: 'Downtime analysis',
        description: 'Explain downtime patterns and affected machines/work orders from supplied records.',
        promptKey: 'manufacturing.downtime_analysis',
        tools: ['manufacturing.work_orders'],
        intentPatterns: [/downtime/i, /machine (down|stop(stage)?|stoppage)/i, /unplanned (stop|halt)/i],
        suggestedActions: ['Machine utilization', 'OEE analysis'],
        followUpQuestions: ['Which machines are down most?', 'What are the top downtime reasons?'],
      },
      {
        key: 'manufacturing.oee.calculation',
        title: 'OEE analysis',
        description: 'Explain OEE components (availability, performance, quality) from available records.',
        promptKey: 'manufacturing.oee_analysis',
        tools: ['manufacturing.work_orders'],
        intentPatterns: [/oee/i, /overall equipment effectiveness/i],
        suggestedActions: ['Downtime analysis', 'Scrap analysis'],
        followUpQuestions: ['Which factor drags OEE most?', 'Which machines are below target?'],
      },
      {
        key: 'manufacturing.schedule.recommendations',
        title: 'Scheduling recommendations',
        description: 'Recommend scheduling adjustments supported by work order and routing records.',
        promptKey: 'manufacturing.schedule_recommendation',
        tools: ['manufacturing.work_orders', 'engineering.routings'],
        intentPatterns: [/schedule (recommendation|s|priority)/i, /reschedule/i, /prioritize (work orders|production)/i],
        suggestedActions: ['Capacity assessment', 'Delay analysis'],
        followUpQuestions: ['Which orders should be prioritized?', 'What capacity is free?'],
      },
      {
        key: 'manufacturing.capacity.assessment',
        title: 'Capacity assessment',
        description: 'Assess machine and plant capacity against the current work order load.',
        promptKey: 'manufacturing.capacity_assessment',
        tools: ['manufacturing.work_orders', 'engineering.routings'],
        intentPatterns: [/capacit(y|ies)/i, /(over|under) (loaded|utilized)/i, /load (level|outlook)/i],
        suggestedActions: ['Machine utilization', 'Scheduling recommendations'],
        followUpQuestions: ['Is capacity sufficient?', 'Which work centers are constrained?'],
      },
    ],
  },
  {
    domain: CopilotDomain.QUALITY,
    label: 'Quality Copilot',
    description: 'NCR, CAPA, inspection, PPAP, FMEA, root-cause, and control-plan assistance grounded in quality records.',
    capabilities: [
      {
        key: 'quality.ncrs.explain',
        title: 'NCR assistance',
        description: 'Explain NCR status, severity, disposition, linked records, and containment actions.',
        promptKey: 'quality.ncr_explanation',
        tools: ['quality.ncrs'],
        intentPatterns: [/ncr/i, /non-?conformance/i, /nonconformity/i],
        suggestedActions: ['Root cause analysis', 'CAPA summary', 'Inspection summary'],
        followUpQuestions: ['What is the disposition?', 'What containment is in place?'],
      },
      {
        key: 'quality.capas.summary',
        title: 'CAPA summary',
        description: 'Summarize CAPA root cause, actions, verification, and effectiveness evidence.',
        promptKey: 'quality.capa_summary',
        tools: ['quality.capas'],
        intentPatterns: [/capa/i, /corrective action/i, /preventive action/i],
        suggestedActions: ['Root cause analysis', 'Control plan review'],
        followUpQuestions: ['Is the CAPA effective?', 'Which actions are open?'],
      },
      {
        key: 'quality.inspections.summary',
        title: 'Inspection summary',
        description: 'Summarize inspections and cite quality records, plans, and NCR/CAPA links.',
        promptKey: 'quality.inspection_summary',
        tools: ['quality.ncrs'],
        intentPatterns: [/inspection (summary|results|report)/i, /inspect(ed|ion) (results|status)/i, /quality (inspection|control) results/i],
        suggestedActions: ['NCR assistance', 'PPAP readiness'],
        followUpQuestions: ['What was inspected?', 'Were there failures?'],
      },
      {
        key: 'quality.ppap.readiness',
        title: 'PPAP/APQP readiness',
        description: 'Guide PPAP/APQP checklist readiness using supplied deliverables and milestones.',
        promptKey: 'quality.ppap_checklist_guidance',
        tools: ['quality.capas', 'engineering.drawings'],
        intentPatterns: [/ppap/i, /apqp/i, /part approval/i, /production part approval/i],
        suggestedActions: ['Inspection summary', 'FMEA assistance'],
        followUpQuestions: ['Which deliverables are missing?', 'What is the PPAP level?'],
      },
      {
        key: 'quality.fmea.assistance',
        title: 'FMEA assistance',
        description: 'Assist with failure modes, effects, causes, RPN, and recommended actions.',
        promptKey: 'quality.fmea_assistance',
        tools: ['quality.capas', 'knowledge.search'],
        intentPatterns: [/fmea/i, /failure mode/i, /rpn/i, /risk priority/i],
        suggestedActions: ['Root cause analysis', 'Control plan review'],
        followUpQuestions: ['Which failure modes have high RPN?', 'What actions reduce risk?'],
      },
      {
        key: 'quality.root_cause.analysis',
        title: 'Root cause analysis',
        description: 'Guide structured root cause analysis using NCR and CAPA evidence.',
        promptKey: 'quality.root_cause_analysis',
        tools: ['quality.ncrs', 'quality.capas'],
        intentPatterns: [/root cause/i, /why did (this |it )?fail/i, /5 why/i, /cause analysis/i],
        suggestedActions: ['NCR assistance', 'CAPA summary'],
        followUpQuestions: ['What evidence supports the cause?', 'Which corrective actions follow?'],
      },
      {
        key: 'quality.control_plans.review',
        title: 'Control plan review',
        description: 'Review control plans and recommend inspection/verification coverage.',
        promptKey: 'quality.control_plan_review',
        tools: ['quality.capas', 'knowledge.search'],
        intentPatterns: [/control plan/i, /inspection plan/i, /verification plan/i],
        suggestedActions: ['FMEA assistance', 'Inspection summary'],
        followUpQuestions: ['Which characteristics are controlled?', 'Is the plan current?'],
      },
    ],
  },
  {
    domain: CopilotDomain.COMMERCIAL,
    label: 'Commercial Copilot',
    description: 'RFQ, quotation, customer-history, margin, risk, and delivery-feasibility assistance.',
    capabilities: [
      {
        key: 'commercial.rfqs.assessment',
        title: 'RFQ assessment',
        description: 'Assess RFQ scope, requirements, and readiness for quotation.',
        promptKey: 'commercial.rfq_assessment',
        tools: ['commercial.rfqs'],
        intentPatterns: [/rfq/i, /request for quot(e|ation)/i, /enquir(y|ies)/i],
        suggestedActions: ['Quotation analysis', 'Customer history'],
        followUpQuestions: ['What does the RFQ require?', 'What is the response status?'],
      },
      {
        key: 'commercial.quotations.analysis',
        title: 'Quotation analysis',
        description: 'Analyze quotation structure, pricing, status, and follow-up needs.',
        promptKey: 'commercial.quotation_analysis',
        tools: ['commercial.quotations'],
        intentPatterns: [/quot(e|ation|ations)/i, /quote (analysis|status|details)/i],
        suggestedActions: ['Margin analysis', 'Delivery feasibility'],
        followUpQuestions: ['Which quotes are outstanding?', 'What is the pricing structure?'],
      },
      {
        key: 'commercial.customers.history',
        title: 'Customer history',
        description: 'Summarize a customer commercial and service history across RFQs, quotes, and service requests.',
        promptKey: 'commercial.customer_history',
        tools: ['commercial.rfqs', 'commercial.quotations', 'service.service_requests'],
        intentPatterns: [/customer (history|profile|relationship)/i, /history with (a |the )?customer/i, /customer (activity|engagement)/i],
        suggestedActions: ['Quotation analysis', 'RFQ assessment'],
        followUpQuestions: ['What has the customer ordered?', 'Any open service issues?'],
      },
      {
        key: 'commercial.margins.analysis',
        title: 'Margin analysis',
        description: 'Analyze quotation margins and identify margin risk or opportunity.',
        promptKey: 'commercial.margin_analysis',
        tools: ['commercial.quotations'],
        intentPatterns: [/margin/i, /profitab(le|ility)/i, /gross margin/i],
        suggestedActions: ['Quotation analysis', 'Risk assessment'],
        followUpQuestions: ['Which quotes have thin margins?', 'Where can margin improve?'],
      },
      {
        key: 'commercial.risk.assessment',
        title: 'Commercial risk assessment',
        description: 'Identify commercial risks across RFQs, quotations, and customer posture.',
        promptKey: 'commercial.risk_assessment',
        tools: ['commercial.rfqs', 'commercial.quotations'],
        intentPatterns: [/commercial risk/i, /risk (in|on) (the )?(deal|quote|rfq|order)/i, /deal risk/i],
        suggestedActions: ['Margin analysis', 'Delivery feasibility'],
        followUpQuestions: ['What are the top risks?', 'How likely is the deal?'],
      },
      {
        key: 'commercial.delivery.feasibility',
        title: 'Delivery feasibility',
        description: 'Assess delivery feasibility of quotations against production load.',
        promptKey: 'commercial.delivery_feasibility',
        tools: ['commercial.quotations', 'manufacturing.work_orders'],
        intentPatterns: [/delivery (feasib|date|promise|commitment)/i, /can we deliver/i, /lead time/i],
        suggestedActions: ['Capacity assessment', 'Quotation analysis'],
        followUpQuestions: ['Can we meet the date?', 'What constrains delivery?'],
      },
      {
        key: 'commercial.pipeline.summary',
        title: 'Commercial pipeline summary',
        description: 'Summarize leads, RFQs, quotations, and customer commercial posture.',
        promptKey: 'commercial.pipeline_summary',
        tools: ['commercial.rfqs', 'commercial.quotations'],
        intentPatterns: [/pipeline/i, /commercial (overview|summary|health)/i, /open (rfqs|quotes|opportunities)/i],
        suggestedActions: ['RFQ assessment', 'Quotation analysis'],
        followUpQuestions: ['What is the open pipeline?', 'Which deals need attention?'],
      },
    ],
  },
  {
    domain: CopilotDomain.PROJECT,
    label: 'Project Copilot',
    description: 'Project health, milestone, delay, resource, and risk assistance.',
    capabilities: [
      {
        key: 'project.health.assessment',
        title: 'Project health assessment',
        description: 'Assess overall project health from schedule, scope, and quality signals.',
        promptKey: 'project.health_assessment',
        tools: ['project.projects'],
        intentPatterns: [/project health/i, /how is (the )?project (doing|going)/i, /health (of )?(the )?project/i],
        suggestedActions: ['Milestone prediction', 'Delay analysis', 'Risk identification'],
        followUpQuestions: ['What is the project status?', 'What are the main concerns?'],
      },
      {
        key: 'project.milestones.prediction',
        title: 'Milestone prediction',
        description: 'Predict milestone attainment from project progress and delivery signals.',
        promptKey: 'project.milestone_prediction',
        tools: ['project.projects'],
        intentPatterns: [/milestone/i, /on track/i, /will (we |the project )?finish/i, /completion (date|forecast)/i],
        suggestedActions: ['Project health assessment', 'Delay analysis'],
        followUpQuestions: ['Which milestones are at risk?', 'What is the forecast completion?'],
      },
      {
        key: 'project.delays.analysis',
        title: 'Project delay analysis',
        description: 'Analyze project delays, causes, and schedule impact.',
        promptKey: 'project.delay_analysis',
        tools: ['project.projects'],
        intentPatterns: [/project delay/i, /late (project|milestone|delivery)/i, /behind plan/i, /project slippage/i],
        suggestedActions: ['Project health assessment', 'Resource planning'],
        followUpQuestions: ['What is causing the delay?', 'How late is the project?'],
      },
      {
        key: 'project.resources.planning',
        title: 'Resource planning',
        description: 'Review resource allocation and identify planning conflicts.',
        promptKey: 'project.resource_planning',
        tools: ['project.projects', 'engineering.routings'],
        intentPatterns: [/resource (plan|allocation|conflict|overload)/i, /team (workload|capacity)/i],
        suggestedActions: ['Project health assessment', 'Delay analysis'],
        followUpQuestions: ['Where are resources overloaded?', 'Which projects compete for resources?'],
      },
      {
        key: 'project.risks.identification',
        title: 'Project risk identification',
        description: 'Identify project risks from schedule, scope, and linked quality records.',
        promptKey: 'project.risk_identification',
        tools: ['project.projects', 'quality.ncrs'],
        intentPatterns: [/project risk/i, /risks? (for|of|related to) (the )?project/i],
        suggestedActions: ['Project health assessment', 'Milestone prediction'],
        followUpQuestions: ['What are the top project risks?', 'Are quality issues linked?'],
      },
      {
        key: 'project.similar.find',
        title: 'Find similar projects',
        description: 'Find similar projects and cite where the similarity comes from.',
        promptKey: 'project.find_similar_projects',
        tools: ['project.projects'],
        intentPatterns: [/similar projects/i, /find (similar|related) projects/i, /other projects (like|similar to)/i],
        suggestedActions: ['Project health assessment'],
        followUpQuestions: ['Which projects are similar?', 'Why are they similar?'],
      },
    ],
  },
  {
    domain: CopilotDomain.SERVICE,
    label: 'Service Copilot',
    description: 'Service-history, warranty, failure, spare-part, and maintenance assistance.',
    capabilities: [
      {
        key: 'service.history.review',
        title: 'Service history review',
        description: 'Build a concise customer/equipment service timeline from supplied records.',
        promptKey: 'service.customer_service_timeline',
        tools: ['service.service_requests'],
        intentPatterns: [/service (history|timeline|log)/i, /history of (service|visits|requests)/i],
        suggestedActions: ['Warranty analysis', 'Failure diagnosis', 'Maintenance planning'],
        followUpQuestions: ['What service was performed?', 'How many visits occurred?'],
      },
      {
        key: 'service.warranty.analysis',
        title: 'Warranty analysis',
        description: 'Summarize warranty coverage, claims, and service timeline.',
        promptKey: 'service.warranty_summary',
        tools: ['service.service_requests'],
        intentPatterns: [/warranty/i, /warrant(y|ies) (claim|coverage|status)/i],
        suggestedActions: ['Service history review', 'Failure diagnosis'],
        followUpQuestions: ['Is the warranty active?', 'Which claims are open?'],
      },
      {
        key: 'service.failures.diagnosis',
        title: 'Failure diagnosis',
        description: 'Diagnose recurring failure patterns from source service records.',
        promptKey: 'service.failure_pattern_summary',
        tools: ['service.service_requests', 'knowledge.search'],
        intentPatterns: [/fail(ure|ed|ing)/i, /breakdown/i, /recurring (issue|problem|failure)/i, /fault/i],
        suggestedActions: ['Spare part recommendation', 'Maintenance planning'],
        followUpQuestions: ['What fails most often?', 'Are there patterns by machine?'],
      },
      {
        key: 'service.spare_parts.recommendation',
        title: 'Spare part recommendation',
        description: 'Recommend spare parts only when supported by service records or knowledge references.',
        promptKey: 'service.recommended_spare_parts',
        tools: ['service.service_requests', 'knowledge.search'],
        intentPatterns: [/spare parts?/i, /replacement parts?/i, /parts? (needed|required|recommended)/i],
        suggestedActions: ['Failure diagnosis', 'Maintenance planning'],
        followUpQuestions: ['Which parts are recommended?', 'What supports the recommendation?'],
      },
      {
        key: 'service.maintenance.planning',
        title: 'Maintenance planning',
        description: 'Summarize maintenance history and upcoming service considerations.',
        promptKey: 'service.maintenance_history',
        tools: ['service.service_requests'],
        intentPatterns: [/maintenance (history|plan|schedule|due)/i, /when (was|is) (the )?(maintenance|service)/i, /next service/i],
        suggestedActions: ['Service history review', 'Warranty analysis'],
        followUpQuestions: ['When is maintenance due?', 'Which assets need attention?'],
      },
      {
        key: 'service.breakdown.assistance',
        title: 'Breakdown assistance',
        description: 'Provide troubleshooting guidance for breakdowns grounded in service and knowledge records.',
        promptKey: 'service.breakdown_assistance',
        tools: ['service.service_requests', 'knowledge.search'],
        intentPatterns: [/breakdown/i, /machine (down|not working|stopped)/i, /emergency (service|repair)/i, /troubleshoot/i],
        suggestedActions: ['Failure diagnosis', 'Spare part recommendation'],
        followUpQuestions: ['What should be checked first?', 'Have similar breakdowns occurred?'],
      },
    ],
  },
  {
    domain: CopilotDomain.EXECUTIVE,
    label: 'Executive Copilot',
    description: 'Dashboard, KPI, cost, revenue, portfolio, risk, and management-briefing assistance.',
    capabilities: [
      {
        key: 'executive.dashboard.briefing',
        title: 'Dashboard briefing',
        description: 'Create a concise enterprise briefing by summarizing existing platform/BI context.',
        promptKey: 'executive.dashboard_briefing',
        tools: ['analytics.bi_query'],
        intentPatterns: [/dashboard briefing/i, /executive (briefing|summary|overview)/i, /morning (brief|briefing)/i],
        suggestedActions: ['KPI explanation', 'Cost trends', 'Revenue overview'],
        followUpQuestions: ['What changed this week?', 'What needs attention today?'],
      },
      {
        key: 'executive.kpi.explanation',
        title: 'KPI explanation',
        description: 'Explain KPI definitions, values, and drivers from supplied BI context.',
        promptKey: 'executive.kpi_explanation',
        tools: ['analytics.bi_query'],
        intentPatterns: [/kpi/i, /key performance indicator/i, /how is .* measured/i],
        suggestedActions: ['Dashboard briefing', 'Cost trends'],
        followUpQuestions: ['How is the KPI trending?', 'What drives it?'],
      },
      {
        key: 'executive.costs.trends',
        title: 'Cost trends',
        description: 'Summarize cost trends from supplied BI or finance context.',
        promptKey: 'executive.cost_trends',
        tools: ['analytics.bi_query'],
        intentPatterns: [/cost (trend|overview|summary|analysis)/i, /spend(ing)? (trend|by)/i, /costs? (this|last) (month|quarter)/i],
        suggestedActions: ['KPI explanation', 'Revenue overview'],
        followUpQuestions: ['Where are costs rising?', 'What drives the trend?'],
      },
      {
        key: 'executive.revenue.overview',
        title: 'Revenue overview',
        description: 'Summarize revenue and commercial context from supplied BI or commercial records.',
        promptKey: 'executive.revenue_overview',
        tools: ['analytics.bi_query'],
        intentPatterns: [/revenue/i, /sales (overview|summary|by)/i, /order intake/i, /booking(s)?/i],
        suggestedActions: ['Dashboard briefing', 'Cost trends'],
        followUpQuestions: ['How is revenue trending?', 'What is the pipeline impact?'],
      },
      {
        key: 'executive.portfolio.health',
        title: 'Portfolio health',
        description: 'Summarize project portfolio posture, risks, and late work.',
        promptKey: 'executive.project_portfolio_summary',
        tools: ['analytics.bi_query', 'project.projects'],
        intentPatterns: [/portfolio/i, /program (health|summary|overview)/i, /all projects/i],
        suggestedActions: ['Risk summary', 'Dashboard briefing'],
        followUpQuestions: ['Which projects are at risk?', 'What is the late-work exposure?'],
      },
      {
        key: 'executive.risks.summary',
        title: 'Enterprise risk summary',
        description: 'Summarize enterprise risks and recommended review actions.',
        promptKey: 'executive.risk_summary',
        tools: ['analytics.bi_query', 'project.projects'],
        intentPatterns: [/enterprise (risk|risks)/i, /risk summary/i, /top risks/i, /risk register/i],
        suggestedActions: ['Portfolio health', 'Dashboard briefing'],
        followUpQuestions: ['What are the top risks?', 'What actions are recommended?'],
      },
      {
        key: 'executive.briefing.management',
        title: 'Management briefing',
        description: 'Create a management health briefing from existing platform/BI context.',
        promptKey: 'executive.company_health_summary',
        tools: ['analytics.bi_query'],
        intentPatterns: [/management (brief|briefing|summary)/i, /company health/i, /business (health|review)/i],
        suggestedActions: ['Dashboard briefing', 'KPI explanation'],
        followUpQuestions: ['How is the company performing?', 'What needs a decision?'],
      },
    ],
  },
];

export function findCopilot(domain: CopilotDomain): CopilotDefinition | undefined {
  return COPILOT_CATALOGUE.find((copilot) => copilot.domain === domain);
}

export function findCapability(domain: CopilotDomain, capabilityKey: string): CopilotCapability | undefined {
  return findCopilot(domain)?.capabilities.find((capability) => capability.key === capabilityKey);
}

export function detectCapability(domain: CopilotDomain, message: string): CopilotCapability | undefined {
  const copilot = findCopilot(domain);
  if (!copilot) return undefined;

  const best = copilot.capabilities.find((capability) =>
    capability.intentPatterns.some((pattern) => pattern.test(message)),
  );

  return best ?? copilot.capabilities[0];
}
